services:
  # app:
  #   build:
  #     context: .
  #   container_name: laravel-app
  #   volumes:
  #     - .:/var/www
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #   environment:
  #     DB_CONNECTION: pgsql
  #     DB_HOST: db
  #     DB_PORT: 5432
  #     DB_DATABASE: test_1_laravel_bd
  #     DB_USERNAME: test_1_laravel_user
  #     DB_PASSWORD: test-1-secret123

  db:
    image: postgres:16
    container_name: pg-db
    restart: always
    environment:
      POSTGRES_DB: test_1_laravel_bd
      POSTGRES_USER: test_1_laravel_user
      POSTGRES_PASSWORD: test-1-secret123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  pgdata:
